# Copyright (C) 2023 Light, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ignores:
  - "@hookform/resolvers"
  - "@storybook/addon-styling"
  - zod
  - "@babel/core"
  - "@lightdotso/eslint-config"
  - "@lightdotso/tailwindcss"
  - "@storybook/addon-actions"
  - "@storybook/addon-backgrounds"
  - "@storybook/addon-docs"
  - "@storybook/addon-essentials"
  - "@storybook/addon-interactions"
  - "@storybook/addon-links"
  - "@storybook/addon-measure"
  - "@storybook/addon-outline"
  - "@storybook/addon-postcss"
  - "@storybook/addons"
  - "@storybook/channel-postmessage"
  - "@storybook/channel-websocket"
  - "@storybook/client-api"
  - "@storybook/nextjs"
  - "@storybook/preview-api"
  - "@storybook/preview-web"
  - "@storybook/testing-library"
  - shadcn-ui
  - unist-builder
  - unist-util-visit
  - tailwindcss-animate
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
