ignores:
  - "@hookform/resolvers"
  - "@storybook/addon-styling"
  - zod
  - "@babel/core"
  - "@lightdotso/eslint-config"
  - "@lightdotso/tailwindcss"
  - "@storybook/addon-actions"
  - "@storybook/addon-backgrounds"
  - "@storybook/addon-docs"
  - "@storybook/addon-essentials"
  - "@storybook/addon-interactions"
  - "@storybook/addon-links"
  - "@storybook/addon-measure"
  - "@storybook/addon-outline"
  - "@storybook/addon-postcss"
  - "@storybook/addon-themes"
  - "@storybook/addons"
  - "@storybook/channel-postmessage"
  - "@storybook/channel-websocket"
  - "@storybook/client-api"
  - "@storybook/nextjs"
  - "@storybook/preview-api"
  - "@storybook/preview-web"
  - "@storybook/testing-library"
  - shadcn-ui
  - unist-builder
  - unist-util-visit
  - tailwindcss-animate
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - "@storybook/blocks"
  - "@storybook/theming"
  - storybook-dark-mode
