upgrade: true
reject:
  - "@tanstack/react-query-next-experimental"
  - "@trpc/client"
  - "@trpc/next"
  - "@trpc/react-query"
  - "@trpc/server"
  - lucide-react
  - "@radix-ui/react-alert-dialog"
  - "@radix-ui/react-dialog"
