# fly.toml app configuration file generated for lightdotso-graph on 2023-09-13T09:44:58-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-graph"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  EXPERIMENTAL_SUBGRAPH_VERSION_SWITCHING_MODE = "synced"
  GRAPH_ETHEREUM_CLEANUP_BLOCKS = "true"
  GRAPH_GRAPHQL_ERROR_RESULT_SIZE = "1000000"
  GRAPH_GRAPHQL_WARN_RESULT_SIZE = "1000000"
  GRAPH_LOG = "debug"

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1m0s"

[metrics]
  port = 9040
  path = "/metrics"
