[package]
  name = "lightdotso-solutions"

  version.workspace = true
  edition.workspace = true
  rust-version.workspace = true
  license.workspace = true
  homepage.workspace = true
  repository.workspace = true

[dependencies]
  async-recursion = "1.0.5"
  ethers = { workspace = true }
  eyre = { workspace = true }
  lightdotso-contracts = { workspace = true }
  rand = { workspace = true }
  serde = { workspace = true }
  serde_json = { workspace = true }
  test-fuzz = "4.0.2"
  tokio = { workspace = true }
