# fly.toml app configuration file generated for lightdotso-kafka-exporter on 2023-09-05T01:32:25-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-kafka-exporter"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 9308
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[metrics]
  port = 9308
  path = "/metrics"
