ignores:
  - solc
  - "@changesets/changelog-github"
  - "@commitlint/config-conventional"
  - "@evmts/config"
  - "@evmts/core"
  - "@evmts/ts-plugin"
  - "@evmts/webpack-plugin"
  - "@lightdotso/sequence"
  - "@lightdotso/tsconfig"
  - "@openzeppelin/contracts"
  - "@release-it/keep-a-changelog"
  - "@swc/core"
  - "@types/dotenv"
  - "@types/jest"
  - "@types/react"
  - "@types/react-dom"
  - "@viem/anvil"
  - "@vitest/coverage-v8"
  - abitype
  - autoprefixer
  - commitlint
  - cross-env
  - dotenv
  - dotenv-cli
  - esbuild
  - git-cz
  - inngest-cli
  - lint-staged
  - npm-package-json-lint-config-default
  - postcss
  - react
  - react-dom
  - release-it
  - rimraf
  - sort-package-json
  - tailwindcss
  - tslib
  - tsup
  - vercel
  - viem
  - next
  - "@thunderclient/cli"
  - clean-package
  - execa
