ignores:
  - solc
  - "@changesets/changelog-github"
  - "@commitlint/config-conventional"
  - "@evmts/config"
  - "@evmts/core"
  - "@evmts/ts-plugin"
  - "@evmts/webpack-plugin"
  - "@lightdotso/solutions"
  - "@lightdotso/tsconfig"
  - "@next/eslint-plugin-next"
  - "@openzeppelin/contracts"
  - "@release-it/keep-a-changelog"
  - "@swc/core"
  - "@types/dotenv"
  - "@types/jest"
  - "@types/react"
  - "@types/react-dom"
  - "@typescript-eslint/eslint-plugin"
  - "@typescript-eslint/parser"
  - "@viem/anvil"
  - "@vitest/coverage-v8"
  - abitype
  - autoprefixer
  - commitlint
  - cross-env
  - dotenv
  - dotenv-cli
  - esbuild
  - eslint-config-next
  - eslint-config-turbo
  - eslint-plugin-cypress
  - eslint-plugin-editorconfig
  - eslint-plugin-jsonc
  - eslint-plugin-jsx-a11y
  - eslint-plugin-prettier
  - eslint-plugin-react
  - eslint-plugin-react-hooks
  - eslint-plugin-simple-import-sort
  - eslint-plugin-tailwindcss
  - eslint-plugin-turbo
  - git-cz
  - inngest-cli
  - jsonc-eslint-parser
  - lint-staged
  - npm-package-json-lint-config-default
  - postcss
  - react
  - react-dom
  - release-it
  - rimraf
  - sort-package-json
  - tailwindcss
  - tslib
  - tsup
  - vercel
  - viem
