coverage_service: cobertura_xml
xcodeproj: ios/LightWallet.xcodeproj
scheme: LightWalletTests
source_directory: ios/LightWalletCore/Sources
output_directory: ios/reports
ignore:
  - ios/LightWalletTests/*
  - ios/LightWalletUITests/*
