[alias]
  build-all = ["build", "--workspace"]
  cli = ["run", "--"]
  prisma = ["run", "--package", "embedded-prisma", "--"]
  generate = [
    "run",
    "--package",
    "embedded-prisma",
    "--",
    "generate",
    "--schema=configurations/prisma/prisma/schema-rs.prisma",
  ]
  scopelint = ["run", "--package", "embedded-scopelint", "--"]
  uniffi-bindgen = ["run", "--package", "embedded-uniffi-bindgen", "--"]
  test-all = ["test", "--workspace"]

[build]
  rustflags = [
    "-D",
    "warnings",
    "-D",
    "clippy::expect_used",
    "-D",
    "clippy::unwrap_used",
  ]

[target.x86_64-apple-darwin]
  rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
  rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
