[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
unsound = "deny"
ignore = ["RUSTSEC-2021-0145"]

[bans]
multiple-versions = "deny"
deny = []
skip = [{ name = "syn", version = "=2.0.14" }]
skip-tree = []
allow = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.93
allow = ["Apache-2.0", "MIT", "MPL-2.0"]
deny = []
exceptions = [{ allow = ["Unicode-DFS-2016"], name = "unicode-ident" }]
