[advisories]
vulnerability = "allow"
unmaintained = "allow"
notice = "deny"
unsound = "deny"
ignore = ["RUSTSEC-2021-0145"]

[bans]
multiple-versions = "allow"
deny = []
skip = []
skip-tree = []
allow = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "CC0-1.0",
    "Apache-2.0 WITH LLVM-exception",
    "GPL-3.0"
]
deny = []
exceptions = [{ allow = ["Unicode-DFS-2016"], name = "unicode-ident" }]
