[toolchain]
  channel = "nightly-2023-09-03"
  targets = [
    "aarch64-linux-android",
    "armv7-linux-androideabi",
    "i686-linux-android",
    "x86_64-linux-android",
    "aarch64-apple-ios",
    "x86_64-apple-ios",
    "aarch64-apple-ios-sim",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
  ]
  profile = "default"
  components = ["clippy", "rustfmt", "rust-src"]
