ignores:
  - "@types/node"
  - vitest
  - kysely-postgres-js
  - postgres
  - zod
  - prisma-kysely
  - "@types/node"
  - typescript
  - "@lightdotso/tsconfig"
  - "@lightdotso/prisma"
  - "@lightdotso/wagmi"
  - "@prisma/client"
