ignores:
  - "@babel/core"
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - "@types/node"
  - typescript
  - "@babel/core"
  - nextra
  - nextra-theme-docs
  - "@types/node"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - "@next/bundle-analyzer"
  - "@sentry/integrations"
  - "content-collections"
  - "next-themes"
  - "fumadocs-openapi"
  - "@content-collections/next"
  - shiki
