ignores:
  - "@babel/core"
  - "@prisma/client"
  - "@upstash/ratelimit"
  - "@upstash/redis"
  - prisma
  - superjson
  - zod
  - "@lightdotso/prisma"
  - "@lightdotso/tailwindcss"
  - "@types/node"
  - eslint-config-prettier
  - eslint-import-resolver-typescript
  - "@playwright/test"
  - checkly
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - jsonc-eslint-parser
  - "@next/eslint-plugin-next"
  - eslint-plugin-turbo
  - swagger-ui-react
  - "@types/swagger-ui-react"
