[package]
  name = "lightdotso-desktop"

  version.workspace = true
  edition.workspace = true
  rust-version.workspace = true
  license.workspace = true
  homepage.workspace = true
  repository.workspace = true

  # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
  tauri-build = { workspace = true }

[dependencies]
  eyre = { workspace = true }
  serde = { workspace = true }
  serde_json = { workspace = true }
  tauri = { workspace = true }

[features]
  # this feature is used for production builds or when `devPath` points to the filesystem
  # DO NOT REMOVE!!
  custom-protocol = ["tauri/custom-protocol"]
