# fly.toml app configuration file generated for lightdotso-grafana on 2023-07-17T01:07:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-grafana"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[env]
  GF_FEATURE_TOGGLES_ENABLE = "publicDashboards"
  GF_INSTALL_PLUGINS = "grafana-worldmap-panel,grafana-clock-panel"
  GF_SERVER_ROOT_URL = "https://grafana.light.so"

[[mounts]]
  source = "grafana_storage"
  destination = "/var/lib/grafana"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200
