# fly.toml app configuration file generated for lightdotso-grafana-agent on 2023-09-08T04:41:10-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-grafana-agent"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 4317
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.health]
    port = 12345
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "get"
    path = "/-/healthy"
