# fly.toml app configuration file generated for lightdotso-otel-collector on 2023-08-18T10:47:01-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-otel-collector"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 4317
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
