ignores:
  - "@lightdotso/background"
  - "@lightdotso/content"
  - "@lightdotso/inpage"
  - "@lightdotso/popup"
  - "@lightdotso/resources"
  - "@lightdotso/eslint-config"
  - "@lightdotso/tsconfig"
  - typescript
  - web-ext
