ignores:
  - "@babel/core"
  - "@lightdotso/kysely"
  - "@lightdotso/prisma"
  - "@lightdotso/styles"
  - "@next-auth/prisma-adapter"
  - "@prisma/client"
  - "@radix-ui/react-accordion"
  - "@radix-ui/react-slot"
  - "@tanstack/react-query-devtools"
  - "@tanstack/react-query-next-experimental"
  - "@types/node"
  - class-variance-authority
  - lucide-react
  - superjson
  - tailwindcss-animate
  - typescript
  - "@lightdotso/eslint-config"
  - "@types/node"
  - typescript
  - wait-port
  - "@playwright/test"
  - "@types/react-dom"
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - next-auth
