[package]
  name = "lightdotso-rspc"

  version.workspace = true
  edition.workspace = true
  rust-version.workspace = true
  license.workspace = true
  homepage.workspace = true
  repository.workspace = true

[dependencies]
  async-stream = { workspace = true }
  lightdotso-db = { workspace = true }
  lightdotso-prisma = { workspace = true }
  lightdotso-tracing = { workspace = true }
  rspc = { workspace = true }
  serde = { workspace = true }
