name: Turbo Trigger
inputs:
  workspace:
    description: Name for npm package name
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch Head
      uses: actions/checkout@v3
      with:
        fetch-depth: 3
    - name: Turbo
      id: turbo
      run: |
        npx turbo-ignore ${{ inputs.workspace }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
