name: Turbo Trigger
inputs:
  workspace:
    description: Name for npm package name
    required: true
outputs:
  trigger:
    description: "Boolean value to trigger or not trigger the workflow"
    value: ${{ steps.turbo.outputs.trigger }}
runs:
  using: "composite"
  steps:
    - name: Turbo Pull Request
      id: turbo
      shell: bash
      run: |
        git rev-parse HEAD
        git log
        npx turbo-ignore ${{ inputs.workspace }} && echo "trigger=false" >> "$GITHUB_OUTPUT" || echo "trigger=true" >> "$GITHUB_OUTPUT"
