# fly.toml app configuration file generated for lightdotso-ipfs on 2023-09-13T09:18:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-ipfs"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]

[env]
  DATA = "/data"
  GOLOG_LOG_FMT = "json"
  GOLOG_LOG_LEVEL = "info"
  IPFS_PATH = "/data/ipfs"
  IPFS_PROFILE = "server"

[[mounts]]
  source = "ipfs_data"
  destination = "/data/ipfs"

[[services]]
  protocol = "tcp"
  internal_port = 4001

  [[services.ports]]
    port = 4001
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 0

[[services]]
  protocol = "tcp"
  internal_port = 4002

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 0

[[services]]
  protocol = "udp"
  internal_port = 4001

  [[services.ports]]
    port = 4001
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 0

[[services]]
  protocol = "udp"
  internal_port = 4003

  [[services.ports]]
    port = 4003
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 0
