/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "version", input: never, result: string } | 
        { key: "wallets", input: never, result: ExtendedWallet[] },
    mutations: 
        { key: "emptyInput", input: EmptyInput, result: null },
    subscriptions: 
        { key: "pings", input: never, result: string }
};

export type EmptyInput = { content: string }

export type ExtendedWallet = { chain_id: string }
