/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


/** OneOf type helpers */
export type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
export type XOR<T, U> = (T | U) extends object ? (Without<T, U> & U) | (Without<U, T> & T) : T | U;
export type OneOf<T extends any[]> = T extends [infer Only] ? Only : T extends [infer A, infer B, ...infer Rest] ? OneOf<[XOR<A, B>, ...Rest]> : never;

export interface paths {
  "/auth/logout": {
    /**
     * Logout a session
     * @description Logout a session
     */
    post: operations["v1_auth_logout_handler"];
  };
  "/auth/nonce": {
    /**
     * Get a auth nonce
     * @description Get a auth nonce
     */
    get: operations["v1_auth_nonce_handler"];
  };
  "/auth/session": {
    /**
     * Get a session
     * @description Get a session
     */
    get: operations["v1_auth_session_handler"];
  };
  "/auth/verify": {
    /**
     * Verify a auth
     * @description Verify a auth
     */
    post: operations["v1_auth_verify_handler"];
  };
  "/check": {
    /**
     * Check if the server is running.
     * @description Check if the server is running.
     */
    get: operations["handler"];
  };
  "/configuration/get": {
    /**
     * Get a configuration
     * @description Get a configuration
     */
    get: operations["v1_configuration_get_handler"];
  };
  "/configuration/list": {
    /**
     * Returns a list of configurations.
     * @description Returns a list of configurations.
     */
    get: operations["v1_configuration_list_handler"];
  };
  "/feedback/create": {
    /**
     * Create a feedback
     * @description Create a feedback
     */
    post: operations["v1_feedback_post_handler"];
  };
  "/health": {
    /**
     * Check the health of the server.
     * @description Check the health of the server.
     */
    get: operations["handler"];
  };
  "/notification/get": {
    /**
     * Get a notification
     * @description Get a notification
     */
    get: operations["v1_notification_get_handler"];
  };
  "/notification/list": {
    /**
     * Returns a list of notifications.
     * @description Returns a list of notifications.
     */
    get: operations["v1_notification_list_handler"];
  };
  "/notification/read": {
    /**
     * Read a list of notifications
     * @description Read a list of notifications
     */
    post: operations["v1_notification_read_handler"];
  };
  "/paymaster/get": {
    /**
     * Get a paymaster
     * @description Get a paymaster
     */
    get: operations["v1_paymaster_get_handler"];
  };
  "/paymaster/list": {
    /**
     * Returns a list of paymasters.
     * @description Returns a list of paymasters.
     */
    get: operations["v1_paymaster_list_handler"];
  };
  "/paymaster_operation/get": {
    /**
     * Get a paymaster
     * @description Get a paymaster
     */
    get: operations["v1_paymaster_operation_get_handler"];
  };
  "/paymaster_operation/list": {
    /**
     * Returns a list of paymasters.
     * @description Returns a list of paymasters.
     */
    get: operations["v1_paymaster_operation_list_handler"];
  };
  "/portfolio/get": {
    /**
     * Get a portfolio
     * @description Get a portfolio
     */
    get: operations["v1_portfolio_get_handler"];
  };
  "/signature/create": {
    /**
     * Create a signature
     * @description Create a signature
     */
    post: operations["v1_signature_post_handler"];
  };
  "/signature/get": {
    /**
     * Get a signature
     * @description Get a signature
     */
    get: operations["v1_signature_get_handler"];
  };
  "/signature/list": {
    /**
     * Returns a list of signatures.
     * @description Returns a list of signatures.
     */
    get: operations["v1_signature_list_handler"];
  };
  "/support_request/create": {
    /**
     * Create a support_request
     * @description Create a support_request
     */
    post: operations["v1_support_request_post_handler"];
  };
  "/token/get": {
    /**
     * Get a token
     * @description Get a token
     */
    get: operations["v1_token_get_handler"];
  };
  "/token/list": {
    /**
     * Returns a list of tokens.
     * @description Returns a list of tokens.
     */
    get: operations["v1_token_list_handler"];
  };
  "/token/list/count": {
    /**
     * Returns a count of list of tokens.
     * @description Returns a count of list of tokens.
     */
    get: operations["v1_token_list_count_handler"];
  };
  "/token_price/get": {
    /**
     * Get a token_price
     * @description Get a token_price
     */
    get: operations["v1_token_price_get_handler"];
  };
  "/transaction/get": {
    /**
     * Get a transaction
     * @description Get a transaction
     */
    get: operations["v1_transaction_get_handler"];
  };
  "/transaction/list": {
    /**
     * Returns a list of transactions.
     * @description Returns a list of transactions.
     */
    get: operations["v1_transaction_list_handler"];
  };
  "/transaction/list/count": {
    /**
     * Returns a count of list of transactions.
     * @description Returns a count of list of transactions.
     */
    get: operations["v1_transaction_list_count_handler"];
  };
  "/user/get": {
    /**
     * Get a user
     * @description Get a user
     */
    get: operations["v1_user_get_handler"];
  };
  "/user_operation/create": {
    /**
     * Create a user operation
     * @description Create a user operation
     */
    post: operations["v1_user_operation_post_handler"];
  };
  "/user_operation/get": {
    /**
     * Get a user operation
     * @description Get a user operation
     */
    get: operations["v1_user_operation_get_handler"];
  };
  "/user_operation/list": {
    /**
     * Returns a list of user operations.
     * @description Returns a list of user operations.
     */
    get: operations["v1_user_operation_list_handler"];
  };
  "/user_operation/list/count": {
    /**
     * Returns a count of user operations.
     * @description Returns a count of user operations.
     */
    get: operations["v1_user_operation_list_count_handler"];
  };
  "/user_operation/nonce": {
    /**
     * Get a user operation nonce
     * @description Get a user operation nonce
     */
    get: operations["v1_user_operation_nonce_handler"];
  };
  "/user_operation/signature": {
    /**
     * Check a user operation for its validity and return the computed signature if valid.
     * @description Check a user operation for its validity and return the computed signature if valid.
     */
    get: operations["v1_user_operation_signature_handler"];
  };
  "/user_operation/update": {
    /**
     * Get a user operation
     * @description Get a user operation
     */
    post: operations["v1_user_operation_update_handler"];
  };
  "/wallet/create": {
    /**
     * Create a wallet
     * @description Create a wallet
     */
    post: operations["v1_wallet_post_handler"];
  };
  "/wallet/get": {
    /**
     * Get a wallet
     * @description Get a wallet
     */
    get: operations["v1_wallet_get_handler"];
  };
  "/wallet/list": {
    /**
     * Returns a list of wallets.
     * @description Returns a list of wallets.
     */
    get: operations["v1_wallet_list_handler"];
  };
  "/wallet/list/count": {
    /**
     * Returns a count of list of wallets.
     * @description Returns a count of list of wallets.
     */
    get: operations["v1_wallet_list_count_handler"];
  };
  "/wallet/settings/get": {
    /**
     * Get a wallet_settings
     * @description Get a wallet_settings
     */
    get: operations["v1_wallet_settings_get_handler"];
  };
  "/wallet/settings/update": {
    /**
     * Create a wallet_settings
     * @description Create a wallet_settings
     */
    post: operations["v1_wallet_settings_post_handler"];
  };
  "/wallet/tab": {
    /**
     * Get a wallet tab
     * @description Get a wallet tab
     */
    get: operations["v1_wallet_tab_handler"];
  };
  "/wallet/update": {
    /**
     * Update a wallet
     * @description Update a wallet
     */
    put: operations["v1_wallet_update_handler"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Auth operation errors */
    AuthError: OneOf<[{
      BadRequest: string;
    }, {
      /** @description Auth not found by id. */
      NotFound: string;
    }, {
      /** @description Internal error. */
      InternalError: string;
    }]>;
    /** @description Auth nonce. */
    AuthNonce: {
      nonce: string;
    };
    /** @description The session. */
    AuthSession: {
      /** @description The session expiration. */
      expiration: string;
      /** @description The session id. */
      id: string;
    };
    AuthVerifyPostRequestParams: {
      message: string;
      signature: string;
    };
    /** @description Configuration root type. */
    Configuration: {
      /** @description The address of the configuration. */
      address: string;
      /**
       * Format: int64
       * @description The checkpoint of the configuration.
       */
      checkpoint: number;
      /** @description The id of the configuration. */
      id: string;
      /** @description The image hash of the configuration. */
      image_hash: string;
      /** @description The owners of the configuration. */
      owners: components["schemas"]["ConfigurationOwner"][];
      /**
       * Format: int64
       * @description The threshold of the configuration.
       */
      threshold: number;
    };
    /** @description Configuration errors */
    ConfigurationError: OneOf<[{
      /** @description Configuration query error. */
      BadRequest: string;
    }, {
      /** @description Configuration not found by id. */
      NotFound: string;
    }]>;
    /** @description Configuration Owner. */
    ConfigurationOwner: {
      /** @description The address of the owner. */
      address: string;
      /** @description The id of the owner. */
      id: string;
      /**
       * Format: int32
       * @description The index of the owner.
       */
      index: number;
      /**
       * Format: int64
       * @description The weight of the owner.
       */
      weight: number;
    };
    /** @description Feedback root type. */
    Feedback: {
      /** @description The emoji of the feedback. */
      emoji: string;
      /** @description The text of the feedback. */
      text: string;
    };
    /** @description Feedback error */
    FeedbackError: OneOf<[{
      /** @description Feedback bad request error. */
      BadRequest: string;
    }, {
      /** @description Feedback not found by id. */
      NotFound: string;
    }]>;
    FeedbackPostRequestParams: {
      feedback: components["schemas"]["Feedback"];
    };
    /** @description Notification root type. */
    Notification: {
      /** @description The id of the notification to read for. */
      id: string;
    };
    /** @description Notification operation errors */
    NotificationError: OneOf<[{
      /** @description Notification query error. */
      BadRequest: string;
    }, {
      /** @description Notification not found by id. */
      NotFound: string;
    }]>;
    /** @description Item to request. */
    NotificationReadRequest: {
      /** @description The id of the notification to read for. */
      id: string;
    };
    NotificationReadRequestParams: {
      /** @description The array of the notifications to query. */
      notifications: components["schemas"]["NotificationReadRequest"][];
    };
    /**
     * @description Wallet owner.
     * @example {
     *   "address": "0x4fd9D0eE6D6564E80A9Ee00c0163fC952d0A45Ed",
     *   "weight": 1
     * }
     */
    Owner: {
      /** @description The address of the owner. */
      address: string;
      /**
       * Format: int32
       * @description The weight of the owner.
       */
      weight: number;
    };
    /** @description Paymaster root type. */
    Paymaster: {
      /** @description The address of the paymaster. */
      address: string;
    };
    /** @description Paymaster operation errors */
    PaymasterError: OneOf<[{
      /** @description Paymaster query error. */
      BadRequest: string;
    }, {
      /** @description Paymaster not found by id. */
      NotFound: string;
    }]>;
    /** @description PaymasterOperation root type. */
    PaymasterOperation: {
      /** @description The id of the paymaster operation. */
      id: string;
    };
    /** @description PaymasterOperation errors */
    PaymasterOperationError: OneOf<[{
      /** @description PaymasterOperation query error. */
      BadRequest: string;
    }, {
      /** @description PaymasterOperation not found by id. */
      NotFound: string;
    }]>;
    /** @description Portfolio root type. */
    Portfolio: {
      /**
       * Format: double
       * @description The balance of the portfolio.
       */
      balance: number;
      /**
       * Format: double
       * @description The change of the balance in the last 24 hours.
       */
      balance_change_24h: number;
      /**
       * Format: double
       * @description The percentage change of the balance in the last 24 hours.
       */
      balance_change_24h_percentage: number;
      /** @description The historical balances of the portfolio. */
      balances: components["schemas"]["PortfolioBalanceDate"][];
    };
    /** @description Portfolio to do. */
    PortfolioBalanceDate: {
      /**
       * Format: double
       * @description The balance of the portfolio.
       */
      balance: number;
      /** @description The date of the balance. */
      date: string;
    };
    /** @description Portfolio operation errors */
    PortfolioError: OneOf<[{
      /** @description Portfolio query error. */
      BadRequest: string;
    }, {
      /** @description Portfolio already exists conflict. */
      Conflict: string;
    }]>;
    /** @description Signature root type. */
    Signature: {
      /** @description The owner id of the signature. */
      owner_id: string;
      /** @description The signature of the user operation in hex. */
      signature: string;
      /**
       * Format: int32
       * @description The type of the signature.
       */
      signature_type: number;
    };
    /** @description Signature operation errors */
    SignatureError: OneOf<[{
      /** @description Signature query error. */
      BadRequest: string;
    }, {
      /** @description Signature not found by id. */
      NotFound: string;
    }]>;
    /** @description Signature operation errors */
    SignaturePostRequestParams: {
      signature: components["schemas"]["Signature"];
    };
    /** @description Support Request root type. */
    SupportRequest: {
      /** @description The area of the support_request. */
      area: string;
      /** @description The description of the support_request. */
      description: string;
      /**
       * Format: int32
       * @description The severity of the support_request.
       */
      severity: number;
      /** @description The title of the support_request. */
      title: string;
    };
    /** @description Support_request operation errors */
    SupportRequestError: OneOf<[{
      /** @description Support_request query error. */
      BadRequest: string;
    }, {
      /** @description Support_request not found by id. */
      NotFound: string;
    }]>;
    SupportRequestPostRequestParams: {
      support_request: components["schemas"]["SupportRequest"];
    };
    /** @description Token root type. */
    Token: {
      /** @description The address of the token. */
      address: string;
      /**
       * Format: int64
       * @description The amount of the token.
       */
      amount: number;
      /**
       * Format: double
       * @description The balance of the token in USD.
       */
      balance_usd: number;
      /**
       * Format: int64
       * @description The chain id of the token.
       */
      chain_id: number;
      /**
       * Format: int32
       * @description The decimals of the token.
       */
      decimals: number;
      /** @description The name of the token. */
      name?: string | null;
      /** @description The symbol of the token. */
      symbol: string;
    };
    /** @description Token error. */
    TokenError: OneOf<[{
      /** @description Token query error. */
      BadRequest: string;
    }, {
      /** @description Token not found by id. */
      NotFound: string;
    }]>;
    /** @description Count of list of tokens. */
    TokenListCount: {
      /**
       * Format: int64
       * @description The count of the list of tokens.
       */
      count: number;
    };
    /** @description TokenPrice root type. */
    TokenPrice: {
      /**
       * Format: double
       * @description The price of the token price.
       */
      price: number;
      /**
       * Format: double
       * @description The change of the token price in the last 24 hours.
       */
      price_change_24h: number;
      /**
       * Format: double
       * @description The percentage change of the token price in the last 24 hours.
       */
      price_change_24h_percentage: number;
      /** @description The historical prices of the token price. */
      prices: components["schemas"]["TokenPriceDate"][];
    };
    TokenPriceDate: {
      /** @description The date of the token price. */
      date: string;
      /**
       * Format: double
       * @description The price of the token price.
       */
      price: number;
    };
    /** @description TokenPrice error. */
    TokenPriceError: OneOf<[{
      /** @description TokenPrice query error. */
      BadRequest: string;
    }, {
      /** @description TokenPrice not found by id. */
      NotFound: string;
    }]>;
    /** @description Transaction root type. */
    Transaction: {
      /**
       * Format: int64
       * @description The chain id of the transaction.
       */
      chain_id: number;
      /** @description The hash of the transaction. */
      hash: string;
      /** @description The timestamp of the transaction. */
      timestamp: string;
    };
    /** @description Transaction operation errors */
    TransactionError: OneOf<[{
      /** @description Transaction query error. */
      BadRequest: string;
    }, {
      /** @description Transaction not found by id. */
      NotFound: string;
    }]>;
    /** @description Count of list of user operations. */
    TransactionListCount: {
      /**
       * Format: int64
       * @description The count of the list of user operations..
       */
      count: number;
    };
    /** @description User root type. */
    User: {
      id: string;
    };
    /** @description User operation errors */
    UserError: OneOf<[{
      /** @description User query error. */
      BadRequest: string;
    }, {
      /** @description User not found by id. */
      NotFound: string;
    }]>;
    /** @description User operation root type. */
    UserOperation: {
      call_data: string;
      /** Format: int64 */
      call_gas_limit: number;
      /** Format: int64 */
      chain_id: number;
      hash: string;
      init_code: string;
      /** Format: int64 */
      max_fee_per_gas: number;
      /** Format: int64 */
      max_priority_fee_per_gas: number;
      /** Format: int64 */
      nonce: number;
      paymaster?: components["schemas"]["UserOperationPaymaster"] | null;
      paymaster_and_data: string;
      /** Format: int64 */
      pre_verification_gas: number;
      sender: string;
      signatures: components["schemas"]["UserOperationSignature"][];
      status: string;
      transaction?: components["schemas"]["UserOperationTransaction"] | null;
      /** Format: int64 */
      verification_gas_limit: number;
    };
    /** @description Item to create. */
    UserOperationCreate: {
      call_data: string;
      /** Format: int64 */
      call_gas_limit: number;
      /** Format: int64 */
      chain_id: number;
      hash: string;
      init_code: string;
      /** Format: int64 */
      max_fee_per_gas: number;
      /** Format: int64 */
      max_priority_fee_per_gas: number;
      /** Format: int64 */
      nonce: number;
      paymaster_and_data: string;
      /** Format: int64 */
      pre_verification_gas: number;
      sender: string;
      /** Format: int64 */
      verification_gas_limit: number;
    };
    /** @description User operation operation errors */
    UserOperationError: OneOf<[{
      BadRequest: string;
    }, {
      /** @description User operation not found by id. */
      NotFound: string;
    }]>;
    /** @description Count of list of user operations. */
    UserOperationListCount: {
      /**
       * Format: int64
       * @description The count of the list of user operations..
       */
      count: number;
    };
    /** @description Nonce */
    UserOperationNonce: {
      /**
       * Format: int64
       * @description The hash of the transaction.
       */
      nonce: number;
    };
    /** @description User operation paymaster */
    UserOperationPaymaster: {
      /** @description The address of the paymaster. */
      address: string;
    };
    UserOperationPostRequestParams: {
      signature: components["schemas"]["UserOperationSignature"];
      user_operation: components["schemas"]["UserOperationCreate"];
    };
    /** @description User operation signature */
    UserOperationSignature: {
      /** @description The id of the owner of the signature. */
      owner_id: string;
      /** @description The signature in hex string. */
      signature: string;
      /**
       * Format: int32
       * @description The signature type
       */
      signature_type: number;
    };
    /** @description User operation operation errors */
    UserOperationSuccess: {
      /** @description User operation updated successfully. */
      Updated: string;
    };
    /** @description User operation transaction */
    UserOperationTransaction: {
      /** @description The hash of the transaction. */
      hash: string;
    };
    /** @description Wallet root type. */
    Wallet: {
      /** @description The address of the wallet. */
      address: string;
      /** @description The address of the factory. */
      factory_address: string;
      /** @description The name of the wallet. */
      name: string;
      /** @description The salt of the wallet. */
      salt: string;
    };
    /** @description Wallet operation errors */
    WalletError: OneOf<[{
      /** @description Wallet query error. */
      BadRequest: string;
    }, {
      /** @description Wallet already exists conflict. */
      Conflict: string;
    }, {
      /** @description Wallet not found by id. */
      NotFound: string;
    }, {
      /**
       * @description Wallet configuration is invalid.
       * The threshold is greater than the number of owners.
       * The threshold is 0.
       */
      InvalidConfiguration: string;
    }]>;
    /** @description Count of list of wallets. */
    WalletListCount: {
      /**
       * Format: int64
       * @description The count of the list of wallets.
       */
      count: number;
    };
    WalletPostRequestParams: {
      /**
       * @description The name of the wallet.
       * @default My Wallet
       * @example My Wallet
       */
      name: string;
      /**
       * @description The array of owners of the wallet.
       * @example [
       *   {
       *     "address": "0x4fd9D0eE6D6564E80A9Ee00c0163fC952d0A45Ed",
       *     "weight": 1
       *   }
       * ]
       */
      owners: components["schemas"]["Owner"][];
      /**
       * @description The salt is used to calculate the new wallet address.
       * @default 0x0000000000000000000000000000000000000000000000000000000000000001
       * @example 0x0000000000000000000000000000000000000000000000000000000000000006
       */
      salt: string;
      /**
       * Format: int32
       * @description The threshold of the wallet.
       * @default 1
       * @example 3
       */
      threshold: number;
    };
    WalletPutRequestParams: {
      /**
       * @description The name of the wallet.
       * @default My Wallet
       * @example My Wallet
       */
      name?: string | null;
    };
    /** @description WalletSettings root type. */
    WalletSettings: {
      /** @description The wallet_settings of whether the testnet is enabled. */
      is_enabled_testnet: boolean;
    };
    /** @description WalletSettings operation errors */
    WalletSettingsError: OneOf<[{
      BadRequest: string;
    }, {
      /** @description WalletSettings not found by id. */
      NotFound: string;
    }]>;
    /** @description Optional WalletSettings root type. */
    WalletSettingsOptional: {
      /** @description The update query of wallet_settings of whether the testnet is enabled. */
      is_enabled_testnet?: boolean | null;
    };
    WalletSettingsPostRequestParams: {
      wallet_settings: components["schemas"]["WalletSettingsOptional"];
    };
    /** @description WalletTab to do. */
    WalletTab: {
      /**
       * Format: int64
       * @description The number of owners of the wallet.
       */
      owner_count: number;
      /**
       * Format: int64
       * @description The number of transactions of the wallet.
       */
      transaction_count: number;
      /**
       * Format: int64
       * @description The pending number of user_operations of the wallet.
       */
      user_operation_count: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Logout a session
   * @description Logout a session
   */
  v1_auth_logout_handler: {
    responses: {
      /** @description Auth logout returned successfully */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Auth logout not succeeded */
      404: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
    };
  };
  /**
   * Get a auth nonce
   * @description Get a auth nonce
   */
  v1_auth_nonce_handler: {
    responses: {
      /** @description Auth nonce returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["AuthNonce"];
        };
      };
      /** @description Auth nonce not found */
      404: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
    };
  };
  /**
   * Get a session
   * @description Get a session
   */
  v1_auth_session_handler: {
    responses: {
      /** @description Auth session returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["AuthSession"];
        };
      };
      /** @description Auth session not found */
      404: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
    };
  };
  /**
   * Verify a auth
   * @description Verify a auth
   */
  v1_auth_verify_handler: {
    parameters: {
      query: {
        user_address: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthVerifyPostRequestParams"];
      };
    };
    responses: {
      /** @description Auth verified successfully */
      200: {
        content: {
          "application/json": components["schemas"]["AuthNonce"];
        };
      };
      /** @description Invalid Configuration */
      400: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
      /** @description Auth already exists */
      409: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
      /** @description Auth internal error */
      500: {
        content: {
          "application/json": components["schemas"]["AuthError"];
        };
      };
    };
  };
  /**
   * Check the health of the server.
   * @description Check the health of the server.
   */
  handler: {
    responses: {
      /** @description Health returned successfully */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get a configuration
   * @description Get a configuration
   */
  v1_configuration_get_handler: {
    parameters: {
      query: {
        /** @description The address of the configuration to query. */
        address: string;
        /** @description The optional checkpoint to filter by. */
        checkpoint?: number | null;
      };
    };
    responses: {
      /** @description Configuration returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Configuration"];
        };
      };
      /** @description Configuration not found */
      404: {
        content: {
          "application/json": components["schemas"]["ConfigurationError"];
        };
      };
    };
  };
  /**
   * Returns a list of configurations.
   * @description Returns a list of configurations.
   */
  v1_configuration_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first configuration to return. */
        offset?: number | null;
        /** @description The maximum number of configurations to return. */
        limit?: number | null;
      };
    };
    responses: {
      /** @description Configurations returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Configuration"][];
        };
      };
      /** @description Configurations bad request */
      500: {
        content: {
          "application/json": components["schemas"]["ConfigurationError"];
        };
      };
    };
  };
  /**
   * Create a feedback
   * @description Create a feedback
   */
  v1_feedback_post_handler: {
    parameters: {
      query: {
        /** @description The id of the user to query. */
        user_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FeedbackPostRequestParams"];
      };
    };
    responses: {
      /** @description Feedback created successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Feedback"];
        };
      };
      /** @description Feedback internal error */
      500: {
        content: {
          "application/json": components["schemas"]["FeedbackError"];
        };
      };
    };
  };
  /**
   * Get a notification
   * @description Get a notification
   */
  v1_notification_get_handler: {
    parameters: {
      query: {
        /** @description The id of the notification to get. */
        notification_id: string;
      };
    };
    responses: {
      /** @description Notification returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Notification"];
        };
      };
      /** @description Notification not found */
      404: {
        content: {
          "application/json": components["schemas"]["NotificationError"];
        };
      };
    };
  };
  /**
   * Returns a list of notifications.
   * @description Returns a list of notifications.
   */
  v1_notification_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first notification to return. */
        offset?: number | null;
        /** @description The maximum number of notifications to return. */
        limit?: number | null;
      };
    };
    responses: {
      /** @description Notifications returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Notification"][];
        };
      };
      /** @description Notification bad request */
      500: {
        content: {
          "application/json": components["schemas"]["NotificationError"];
        };
      };
    };
  };
  /**
   * Read a list of notifications
   * @description Read a list of notifications
   */
  v1_notification_read_handler: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["NotificationReadRequestParams"];
      };
    };
    responses: {
      /** @description Notification created successfully */
      200: {
        content: {
          "text/plain": number;
        };
      };
      /** @description Notification internal error */
      500: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Get a paymaster
   * @description Get a paymaster
   */
  v1_paymaster_get_handler: {
    parameters: {
      query: {
        id: string;
      };
    };
    responses: {
      /** @description Paymaster returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Paymaster"];
        };
      };
      /** @description Paymaster not found */
      404: {
        content: {
          "application/json": components["schemas"]["PaymasterError"];
        };
      };
    };
  };
  /**
   * Returns a list of paymasters.
   * @description Returns a list of paymasters.
   */
  v1_paymaster_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first paymaster to return. */
        offset?: number | null;
        /** @description The maximum number of paymasters to return. */
        limit?: number | null;
      };
    };
    responses: {
      /** @description Paymasters returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Paymaster"][];
        };
      };
      /** @description Paymaster bad request */
      500: {
        content: {
          "application/json": components["schemas"]["PaymasterError"];
        };
      };
    };
  };
  /**
   * Get a paymaster
   * @description Get a paymaster
   */
  v1_paymaster_operation_get_handler: {
    parameters: {
      query: {
        /** @description The address of the paymaster. */
        address: string;
        /** @description The chain id of the paymaster. */
        chain_id: number;
        /** @description The timestamp of the paymaster. */
        valid_after: number;
      };
    };
    responses: {
      /** @description Paymaster Operation returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["PaymasterOperation"];
        };
      };
      /** @description Paymaster Operation not found */
      404: {
        content: {
          "application/json": components["schemas"]["PaymasterOperationError"];
        };
      };
    };
  };
  /**
   * Returns a list of paymasters.
   * @description Returns a list of paymasters.
   */
  v1_paymaster_operation_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first paymaster operation to return. */
        offset?: number | null;
        /** @description The maximum number of paymaster operations to return. */
        limit?: number | null;
      };
    };
    responses: {
      /** @description Paymaster Operations returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["PaymasterOperation"][];
        };
      };
      /** @description Paymaster Operation bad request */
      500: {
        content: {
          "application/json": components["schemas"]["PaymasterOperationError"];
        };
      };
    };
  };
  /**
   * Get a portfolio
   * @description Get a portfolio
   */
  v1_portfolio_get_handler: {
    parameters: {
      query: {
        /** @description The address of the portfolio. */
        address: string;
      };
    };
    responses: {
      /** @description Portfolio returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Portfolio"];
        };
      };
      /** @description Portfolio not found */
      404: {
        content: {
          "application/json": components["schemas"]["PortfolioError"];
        };
      };
    };
  };
  /**
   * Create a signature
   * @description Create a signature
   */
  v1_signature_post_handler: {
    parameters: {
      query: {
        /** @description The hash of the user operation. */
        user_operation_hash: string;
        /** @description The procedure to create(default: OnChain) */
        procedure?: ("Offchain" | "Onchain" | "Erc1271") | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SignaturePostRequestParams"];
      };
    };
    responses: {
      /** @description Signature created successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Signature"];
        };
      };
      /** @description Invalid Configuration */
      400: {
        content: {
          "application/json": components["schemas"]["SignatureError"];
        };
      };
      /** @description Signature already exists */
      409: {
        content: {
          "application/json": components["schemas"]["SignatureError"];
        };
      };
      /** @description Signature internal error */
      500: {
        content: {
          "application/json": components["schemas"]["SignatureError"];
        };
      };
    };
  };
  /**
   * Get a signature
   * @description Get a signature
   */
  v1_signature_get_handler: {
    parameters: {
      query: {
        user_operation_hash: string;
      };
    };
    responses: {
      /** @description Signature returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Signature"];
        };
      };
      /** @description Signature not found */
      404: {
        content: {
          "application/json": components["schemas"]["SignatureError"];
        };
      };
    };
  };
  /**
   * Returns a list of signatures.
   * @description Returns a list of signatures.
   */
  v1_signature_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first signature to return. */
        offset?: number | null;
        /** @description The maximum number of signatures to return. */
        limit?: number | null;
        /** @description The user operation hash to filter by. */
        user_operation_hash?: string | null;
      };
    };
    responses: {
      /** @description Signatures returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Signature"][];
        };
      };
      /** @description Signature bad request */
      500: {
        content: {
          "application/json": components["schemas"]["SignatureError"];
        };
      };
    };
  };
  /**
   * Create a support_request
   * @description Create a support_request
   */
  v1_support_request_post_handler: {
    parameters: {
      query: {
        /** @description The wallet address of the user operation. */
        wallet_address: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SupportRequestPostRequestParams"];
      };
    };
    responses: {
      /** @description SupportRequest created successfully */
      200: {
        content: {
          "application/json": components["schemas"]["SupportRequest"];
        };
      };
      /** @description SupportRequest internal error */
      500: {
        content: {
          "application/json": components["schemas"]["SupportRequestError"];
        };
      };
    };
  };
  /**
   * Get a token
   * @description Get a token
   */
  v1_token_get_handler: {
    parameters: {
      query: {
        /** @description The address of the token. */
        address: string;
        /** @description The chain id of the token. */
        chain_id: number;
      };
    };
    responses: {
      /** @description Token returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Token"];
        };
      };
      /** @description Token not found */
      404: {
        content: {
          "application/json": components["schemas"]["TokenError"];
        };
      };
    };
  };
  /**
   * Returns a list of tokens.
   * @description Returns a list of tokens.
   */
  v1_token_list_handler: {
    parameters: {
      query: {
        /** @description The offset of the first token to return. */
        offset?: number | null;
        /** @description The maximum number of tokens to return. */
        limit?: number | null;
        /** @description The address of the wallet. */
        address: string;
        /** @description The flag to indicate if the token is a spam. */
        is_spam?: boolean | null;
        /** @description The flag to indicate if the token is a testnet token. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description Tokens returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Token"][];
        };
      };
      /** @description Token bad request */
      500: {
        content: {
          "application/json": components["schemas"]["TokenError"];
        };
      };
    };
  };
  /**
   * Returns a count of list of tokens.
   * @description Returns a count of list of tokens.
   */
  v1_token_list_count_handler: {
    parameters: {
      query: {
        /** @description The offset of the first token to return. */
        offset?: number | null;
        /** @description The maximum number of tokens to return. */
        limit?: number | null;
        /** @description The address of the wallet. */
        address: string;
        /** @description The flag to indicate if the token is a spam. */
        is_spam?: boolean | null;
        /** @description The flag to indicate if the token is a testnet token. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description Tokens returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["TokenListCount"];
        };
      };
      /** @description Token bad request */
      500: {
        content: {
          "application/json": components["schemas"]["TokenError"];
        };
      };
    };
  };
  /**
   * Get a token_price
   * @description Get a token_price
   */
  v1_token_price_get_handler: {
    parameters: {
      query: {
        /** @description The address of the token_price. */
        address: string;
        /** @description The chain id of the token_price. */
        chain_id: number;
      };
    };
    responses: {
      /** @description Token returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["TokenPrice"];
        };
      };
      /** @description Token not found */
      404: {
        content: {
          "application/json": components["schemas"]["TokenError"];
        };
      };
    };
  };
  /**
   * Get a transaction
   * @description Get a transaction
   */
  v1_transaction_get_handler: {
    parameters: {
      query: {
        /** @description The transaction hash. */
        transaction_hash: string;
      };
    };
    responses: {
      /** @description Transaction returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Transaction"];
        };
      };
      /** @description Transaction not found */
      404: {
        content: {
          "application/json": components["schemas"]["TransactionError"];
        };
      };
    };
  };
  /**
   * Returns a list of transactions.
   * @description Returns a list of transactions.
   */
  v1_transaction_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first transaction to return. */
        offset?: number | null;
        /** @description The maximum number of transactions to return. */
        limit?: number | null;
        /** @description The sender address to filter by. */
        address?: string | null;
        /** @description The flag to indicate if the transaction is a testnet transaction. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description Transactions returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Transaction"][];
        };
      };
      /** @description Transaction bad request */
      500: {
        content: {
          "application/json": components["schemas"]["TransactionError"];
        };
      };
    };
  };
  /**
   * Returns a count of list of transactions.
   * @description Returns a count of list of transactions.
   */
  v1_transaction_list_count_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first transaction to return. */
        offset?: number | null;
        /** @description The maximum number of transactions to return. */
        limit?: number | null;
        /** @description The sender address to filter by. */
        address?: string | null;
        /** @description The flag to indicate if the transaction is a testnet transaction. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description Transactions returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["TransactionListCount"];
        };
      };
      /** @description Transaction bad request */
      500: {
        content: {
          "application/json": components["schemas"]["TransactionError"];
        };
      };
    };
  };
  /**
   * Get a user
   * @description Get a user
   */
  v1_user_get_handler: {
    parameters: {
      query: {
        address: string;
      };
    };
    responses: {
      /** @description User returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description User not found */
      404: {
        content: {
          "application/json": components["schemas"]["UserError"];
        };
      };
    };
  };
  /**
   * Create a user operation
   * @description Create a user operation
   */
  v1_user_operation_post_handler: {
    parameters: {
      query: {
        chain_id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserOperationPostRequestParams"];
      };
    };
    responses: {
      /** @description User Operation created successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperation"];
        };
      };
      /** @description Invalid Configuration */
      400: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
      /** @description User Operation already exists */
      409: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
      /** @description User Operation internal error */
      500: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Get a user operation
   * @description Get a user operation
   */
  v1_user_operation_get_handler: {
    parameters: {
      query: {
        /** @description The user operation hash to get. */
        user_operation_hash: string;
      };
    };
    responses: {
      /** @description User Operation returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperation"];
        };
      };
      /** @description User Operation not found */
      404: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Returns a list of user operations.
   * @description Returns a list of user operations.
   */
  v1_user_operation_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first user operation to return. */
        offset?: number | null;
        /** @description The maximum number of user operations to return. */
        limit?: number | null;
        /** @description The sender address to filter by. */
        address?: string | null;
        /** @description The status to filter by. */
        status?: ("proposed" | "pending" | "executed" | "reverted") | null;
        /**
         * @description The direction to order by.
         * Default is `asc`.
         */
        order?: ("asc" | "desc") | null;
        /** @description The flag to indicate if the operation is a testnet user operation. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description User Operations returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperation"][];
        };
      };
      /** @description User Operation bad request */
      500: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Returns a count of user operations.
   * @description Returns a count of user operations.
   */
  v1_user_operation_list_count_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first user operation to return. */
        offset?: number | null;
        /** @description The maximum number of user operations to return. */
        limit?: number | null;
        /** @description The sender address to filter by. */
        address?: string | null;
        /** @description The status to filter by. */
        status?: ("proposed" | "pending" | "executed" | "reverted") | null;
        /**
         * @description The direction to order by.
         * Default is `asc`.
         */
        order?: ("asc" | "desc") | null;
        /** @description The flag to indicate if the operation is a testnet user operation. */
        is_testnet?: boolean | null;
      };
    };
    responses: {
      /** @description User Operation count returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperationListCount"];
        };
      };
      /** @description User Operation count bad request */
      500: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Get a user operation nonce
   * @description Get a user operation nonce
   */
  v1_user_operation_nonce_handler: {
    parameters: {
      query: {
        /** @description The chain id to get the user operation nonce for. */
        chain_id: number;
        /** @description The sender address to filter by. */
        address: string;
      };
    };
    responses: {
      /** @description User Operation nonce returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperationNonce"];
        };
      };
      /** @description User Operation nonce not found */
      404: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Check a user operation for its validity and return the computed signature if valid.
   * @description Check a user operation for its validity and return the computed signature if valid.
   */
  v1_user_operation_signature_handler: {
    parameters: {
      query: {
        /** @description The user operation hash to get. */
        user_operation_hash: string;
        /** @description The type of signature to get for. */
        signature_type?: number | null;
      };
    };
    responses: {
      /** @description User Operation signature returned successfully */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description User Operation not found */
      404: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Get a user operation
   * @description Get a user operation
   */
  v1_user_operation_update_handler: {
    parameters: {
      query: {
        /** @description The sender address to filter by. */
        address: string;
      };
    };
    responses: {
      /** @description User Operation updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["UserOperationSuccess"];
        };
      };
      /** @description User Operation not found */
      404: {
        content: {
          "application/json": components["schemas"]["UserOperationError"];
        };
      };
    };
  };
  /**
   * Create a wallet
   * @description Create a wallet
   */
  v1_wallet_post_handler: {
    parameters: {
      query?: {
        /** @description Whether to simulate the wallet creation. */
        simulate?: boolean | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WalletPostRequestParams"];
      };
    };
    responses: {
      /** @description Wallet created successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
      /** @description Invalid Configuration */
      400: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
      /** @description Wallet already exists */
      409: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
      /** @description Wallet internal error */
      500: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
  /**
   * Get a wallet
   * @description Get a wallet
   */
  v1_wallet_get_handler: {
    parameters: {
      query: {
        /** @description The address of the wallet. */
        address: string;
        /** @description The chain id of the wallet. */
        chain_id?: number | null;
      };
    };
    responses: {
      /** @description Wallet returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
      /** @description Wallet not found */
      404: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
  /**
   * Returns a list of wallets.
   * @description Returns a list of wallets.
   */
  v1_wallet_list_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first wallet to return. */
        offset?: number | null;
        /** @description The maximum number of wallets to return. */
        limit?: number | null;
        /** @description A filter to return wallets w/ a given owner. */
        owner?: string | null;
      };
    };
    responses: {
      /** @description Wallets returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Wallet"][];
        };
      };
      /** @description Wallet bad request */
      500: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
  /**
   * Returns a count of list of wallets.
   * @description Returns a count of list of wallets.
   */
  v1_wallet_list_count_handler: {
    parameters: {
      query?: {
        /** @description The offset of the first wallet to return. */
        offset?: number | null;
        /** @description The maximum number of wallets to return. */
        limit?: number | null;
        /** @description A filter to return wallets w/ a given owner. */
        owner?: string | null;
      };
    };
    responses: {
      /** @description Wallets returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["WalletListCount"];
        };
      };
      /** @description Wallet bad request */
      500: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
  /**
   * Get a wallet_settings
   * @description Get a wallet_settings
   */
  v1_wallet_settings_get_handler: {
    parameters: {
      query: {
        /** @description The address of the wallet settings. */
        address: string;
      };
    };
    responses: {
      /** @description WalletSettings returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["WalletSettings"];
        };
      };
      /** @description WalletSettings not found */
      404: {
        content: {
          "application/json": components["schemas"]["WalletSettingsError"];
        };
      };
    };
  };
  /**
   * Create a wallet_settings
   * @description Create a wallet_settings
   */
  v1_wallet_settings_post_handler: {
    parameters: {
      query: {
        /** @description The hash of the wallet settings. */
        address: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WalletSettingsPostRequestParams"];
      };
    };
    responses: {
      /** @description WalletSettings updated successfully */
      200: {
        content: {
          "application/json": components["schemas"]["WalletSettings"];
        };
      };
      /** @description Invalid Configuration */
      400: {
        content: {
          "application/json": components["schemas"]["WalletSettingsError"];
        };
      };
      /** @description WalletSettings already exists */
      409: {
        content: {
          "application/json": components["schemas"]["WalletSettingsError"];
        };
      };
      /** @description WalletSettings internal error */
      500: {
        content: {
          "application/json": components["schemas"]["WalletSettingsError"];
        };
      };
    };
  };
  /**
   * Get a wallet tab
   * @description Get a wallet tab
   */
  v1_wallet_tab_handler: {
    parameters: {
      query: {
        /** @description The address of the wallet. */
        address: string;
        /** @description The chain id of the wallet. */
        chain_id?: number | null;
      };
    };
    responses: {
      /** @description Wallet tab returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["WalletTab"];
        };
      };
      /** @description Wallet tab not found */
      404: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
  /**
   * Update a wallet
   * @description Update a wallet
   */
  v1_wallet_update_handler: {
    parameters: {
      query: {
        /** @description The address of the wallet. */
        address: string;
        /** @description The chain id of the wallet. */
        chain_id?: number | null;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["WalletPutRequestParams"];
      };
    };
    responses: {
      /** @description Wallet returned successfully */
      200: {
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
      /** @description Wallet bad request */
      500: {
        content: {
          "application/json": components["schemas"]["WalletError"];
        };
      };
    };
  };
}
