# fly.toml app configuration file generated for lightdotso-dev on 2023-09-08T12:23:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-dev"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  entrypoint = ["/usr/local/bin/consumer"]

[build]
  image = "ghcr.io/lightdotso/lightdotso:sha-932a618d673d99c3bad07fee8ec8c982208e611c"

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  # [checks]
  #   [checks.health]
  #     port = 9091
  #     type = "http"
  #     interval = "15s"
  #     timeout = "10s"
  #     grace_period = "30s"
  #     method = "get"
  #     path = "/health"

  # [metrics]
  #   port = 9091
  #   path = "/metrics"
