# Copyright (C) 2023 Light, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317 # here we tell OpenTelemetryCollector to listen for metrics submissions from our main app

exporters:
  logging:
    loglevel: debug
  prometheusremotewrite:
    endpoint: https://light.fmp.fiberplane.dev/api/v1/write # This is the endpoint we point it to send to FMP

service: # we define the pipeline the collector needs to go through
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [logging, prometheusremotewrite]

  telemetry:
    logs:
      level: "debug"
