[package]
  name = "embedded-bulloak"

  version.workspace = true
  edition.workspace = true
  rust-version.workspace = true
  license.workspace = true
  homepage.workspace = true
  repository.workspace = true

  publish = false

[dependencies]
  bulloak = "0.8.0"
