[package]
name = "embedded-uniffi-bindgen"
version = "0.1.0"
authors = ["The Firefox Sync Developers <sync-team@mozilla.com>"]
edition = "2021"

license = "GPL-3.0"

publish = false

[dependencies]
uniffi = { workspace = true, features = ["cli"] }
