GRANT ALL PRIVILEGES ON TABLE "TokenPrice" TO dev;
ALTER TABLE "TokenPrice" OWNER TO dev;
GRANT ALL PRIVILEGES ON TABLE "TokenProtocol" TO dev;
ALTER TABLE "TokenProtocol" OWNER TO dev;
GRANT ALL PRIVILEGES ON TABLE "WalletBalance" TO dev;
ALTER TABLE "WalletBalance" OWNER TO dev;
