# fly.toml app configuration file generated for lightdotso-tempo on 2023-09-08T01:44:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-tempo"
primary_region = "sjc"

[build]
  dockerfile = "./Dockerfile"
