# fly.toml app configuration file generated for lightdotso-consumer-node on 2024-07-10T17:46:31+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lightdotso-consumer-node'
primary_region = 'sjc'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  entrypoint = ['/usr/local/bin/consumer']

[build]
  image = 'ghcr.io/lightdotso/lightdotso:latest'

[deploy]
  strategy = 'bluegreen'

[checks]
  [checks.health]
    port = 9091
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[metrics]]
  port = 9091
  path = '/metrics'
