ignores:
  - "@hookform/resolvers"
  - "@storybook/addon-styling"
  - zod
  - "@babel/core"
  - "@lightdotso/tailwindcss"
  - "@storybook/addon-actions"
  - "@storybook/addon-backgrounds"
  - "@storybook/addon-docs"
  - "@storybook/addon-essentials"
  - "@storybook/addon-interactions"
  - "@storybook/addon-links"
  - "@storybook/addon-measure"
  - "@storybook/addon-outline"
  - "@storybook/addon-postcss"
  - "@storybook/addon-themes"
  - "@storybook/addons"
  - "@storybook/channel-postmessage"
  - "@storybook/channel-websocket"
  - "@storybook/client-api"
  - "@storybook/nextjs"
  - "@storybook/preview-api"
  - "@storybook/preview-web"
  - "@storybook/testing-library"
  - shadcn-ui
  - unist-builder
  - unist-util-visit
  - tailwindcss-animate
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - "@storybook/blocks"
  - "@storybook/theming"
  - storybook-dark-mode
  - "@emotion/is-prop-valid"
  - "@radix-ui/react-toast"
  - "@lightdotso/client"
  - "@lightdotso/const"
  - "@lightdotso/demo"
  - "@tanstack/react-table"
  - "@tremor/react"
  - "@lightdotso/svg"
  - vite
  - css-loader
  - "@lightdotso/elements"
  - "@lightdotso/tables"
  - "@lightdotso/templates"
  - wagmi
  - "@lightdotso/wagmi"
  - "@lightdotso/styles"
  - "@storybook/react-vite"
  - "@types/node"
  - next
  - windy-radix-palette
  - "@headlessui/tailwindcss"
  - "@tailwindcss/aspect-ratio"
  - "@tailwindcss/forms"
  - "@tailwindcss/typography"
  - msw-storybook-addon
  - "@lightdotso/msw"
  - "@lightdotso/forms"
  - react-is
  - recharts
  - "@lightdotso/dialogs"
  - "@lightdotso/modals"
  - "@lightdotso/states"
  - "@types/react"
  - "@lightdotso/ui"
