[profile.default]
  leak-timeout = "3000ms"
  retries = { backoff = "exponential", count = 3, delay = "10s" }
  slow-timeout = "3m"

  [[profile.default.overrides]]
    filter = 'test(test_e2e)'
    retries = 10
