ignores:
  - "@hookform/resolvers"
  - "@storybook/addon-styling"
  - zod
  - "@babel/core"
  - "@lightdotso/tailwindcss"
  - shadcn-ui
  - unist-builder
  - unist-util-visit
  - tailwindcss-animate
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - "@emotion/is-prop-valid"
  - "@radix-ui/react-toast"
  - "@types/node"
  - vite
  - "@storybook/blocks"
  - tsup
  - "@lightdotso/const"
  - "@lightdotso/data"
  - "@lightdotso/demo"
  - "@lightdotso/svg"
  - "@lightdotso/types"
  - "@tanstack/react-table"
  - react-blurhash
  - react-icons
  - viem
  - "@hookform/devtools"
  - "@tanstack/react-query-next-experimental"
  - superjson
  - react-is
