# fly.toml app configuration file generated for lightdotso-serve on 2023-07-14T21:36:24-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lightdotso-serve"
primary_region = "sjc"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  entrypoint = ["/usr/local/bin/serve"]

[build]
  image = "ghcr.io/lightdotso/lightdotso:latest"
  auto_rollback = true

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    hard_limit = 250
    soft_limit = 200

[checks]
  [checks.health]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/health"
    port = 3002
    timeout = "10s"
    type = "http"
