ignores:
  - "@babel/core"
  - "@lightdotso/kysely"
  - "@lightdotso/prisma"
  - "@prisma/client"
  - "@tanstack/react-query"
  - "@tanstack/react-query-devtools"
  - "@tanstack/react-query-next-experimental"
  - kysely-postgres-js
  - postgres
  - prisma
  - server-only
  - superjson
  - "@types/node"
  - eslint-config-prettier
  - eslint-import-resolver-typescript
  - "@playwright/test"
  - checkly
  - "@lightdotso/styles"
  - "@lightdotso/ui"
  - connectkit
  - siwe
  - viem
  - wagmi
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - jsonc-eslint-parser
  - "@next/eslint-plugin-next"
  - eslint-plugin-turbo
