# Copyright (C) 2023 Light, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ignores:
  - "@babel/core"
  - "@lightdotso/kysely"
  - "@lightdotso/prisma"
  - "@next-auth/prisma-adapter"
  - "@prisma/client"
  - "@tanstack/react-query-devtools"
  - "@tanstack/react-query-next-experimental"
  - kysely-postgres-js
  - postgres
  - prisma
  - server-only
  - superjson
  - "@types/node"
  - eslint-config-prettier
  - eslint-import-resolver-typescript
  - "@playwright/test"
  - checkly
  - "@lightdotso/auth"
  - "@lightdotso/styles"
  - "@lightdotso/ui"
  - connectkit
  - siwe
  - viem
  - wagmi
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - jsonc-eslint-parser
  - "@next/eslint-plugin-next"
  - eslint-plugin-turbo
