ignores:
  - "@babel/core"
  - "@lightdotso/kysely"
  - "@lightdotso/prisma"
  - "@prisma/client"
  - "@tanstack/react-query"
  - "@tanstack/react-query-devtools"
  - "@tanstack/react-query-next-experimental"
  - kysely-postgres-js
  - postgres
  - prisma
  - server-only
  - superjson
  - "@types/node"
  - "@playwright/test"
  - checkly
  - "@lightdotso/styles"
  - "@lightdotso/ui"
  - siwe
  - viem
  - wagmi
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - "@lightdotso/client"
  - "@lightdotso/params"
  - "@next/bundle-analyzer"
  - "@lightdotso/states"
  - "@sentry-internal/feedback"
  - "@sentry/react"
  - "@sentry/integrations"
  - lucide-react
