#!/bin/sh

[ -n "$CI" ] && exit 0

branch="$(git rev-parse --abbrev-ref HEAD)"

# Check if the branch is main
if [ "$branch" = "main" ]; then
    echo 'Direct push to main is not allowed. Create a pull request instead.'
    exit 1
fi

# Run cspell on changed files compared to origin/main
git diff --name-only origin/main | pnpm cspell --file-list stdin || pnpm run cspell:fix

# Run project-words:lint or project-words:fix
pnpm run project-words:lint || pnpm run project-words:fix
