# From: https://cert-manager.io/docs/configuration/acme/dns01/google/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: light-so-certificate
  namespace: cert-manager
spec:
  secretName: light-so-tls
  issuerRef:
    # The issuer created previously
    name: light-so-issuer
  dnsNames:
    - api.light.so
    - dev.api.light.so
