apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: serve-ingress
spec:
  rules:
    - host: api.light.so
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: serve-service
                port:
                  number: 3002
