// Generated by @wagmi/cli@1.3.0 on 7/6/2023 at 8:00:58 PM
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
} from "wagmi";
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult,
} from "wagmi/actions";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// LightWallet
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const lightWalletABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      {
        name: "anEntryPoint",
        internalType: "contract IEntryPoint",
        type: "address",
      },
    ],
  },
  { type: "error", inputs: [], name: "OnlyOwner" },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "previousAdmin",
        internalType: "address",
        type: "address",
        indexed: false,
      },
      {
        name: "newAdmin",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "AdminChanged",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "beacon",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "BeaconUpgraded",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "version", internalType: "uint8", type: "uint8", indexed: false },
    ],
    name: "Initialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "entryPoint",
        internalType: "contract IEntryPoint",
        type: "address",
        indexed: true,
      },
      {
        name: "owner",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "LightWalletInitialized",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "implementation",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "Upgraded",
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [],
    name: "addDeposit",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "entryPoint",
    outputs: [
      { name: "", internalType: "contract IEntryPoint", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "dest", internalType: "address", type: "address" },
      { name: "value", internalType: "uint256", type: "uint256" },
      { name: "func", internalType: "bytes", type: "bytes" },
    ],
    name: "execute",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "dest", internalType: "address[]", type: "address[]" },
      { name: "func", internalType: "bytes[]", type: "bytes[]" },
    ],
    name: "executeBatch",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "getDeposit",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "getNonce",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [{ name: "anOwner", internalType: "address", type: "address" }],
    name: "initialize",
    outputs: [],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "hash", internalType: "bytes32", type: "bytes32" },
      { name: "signature", internalType: "bytes", type: "bytes" },
    ],
    name: "isValidSignature",
    outputs: [{ name: "magicValue", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "uint256[]", type: "uint256[]" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155BatchReceived",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC1155Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "onERC721Received",
    outputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "owner",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "proxiableUUID",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [{ name: "", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
  },
  {
    stateMutability: "pure",
    type: "function",
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "bytes", type: "bytes" },
      { name: "", internalType: "bytes", type: "bytes" },
    ],
    name: "tokensReceived",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "newImplementation", internalType: "address", type: "address" },
    ],
    name: "upgradeTo",
    outputs: [],
  },
  {
    stateMutability: "payable",
    type: "function",
    inputs: [
      { name: "newImplementation", internalType: "address", type: "address" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "upgradeToAndCall",
    outputs: [],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      {
        name: "userOp",
        internalType: "struct UserOperation",
        type: "tuple",
        components: [
          { name: "sender", internalType: "address", type: "address" },
          { name: "nonce", internalType: "uint256", type: "uint256" },
          { name: "initCode", internalType: "bytes", type: "bytes" },
          { name: "callData", internalType: "bytes", type: "bytes" },
          { name: "callGasLimit", internalType: "uint256", type: "uint256" },
          {
            name: "verificationGasLimit",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "preVerificationGas",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "maxFeePerGas", internalType: "uint256", type: "uint256" },
          {
            name: "maxPriorityFeePerGas",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "paymasterAndData", internalType: "bytes", type: "bytes" },
          { name: "signature", internalType: "bytes", type: "bytes" },
        ],
      },
      { name: "userOpHash", internalType: "bytes32", type: "bytes32" },
      { name: "missingAccountFunds", internalType: "uint256", type: "uint256" },
    ],
    name: "validateUserOp",
    outputs: [
      { name: "validationData", internalType: "uint256", type: "uint256" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      {
        name: "withdrawAddress",
        internalType: "address payable",
        type: "address",
      },
      { name: "amount", internalType: "uint256", type: "uint256" },
    ],
    name: "withdrawDepositTo",
    outputs: [],
  },
  { stateMutability: "payable", type: "receive" },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// LightWalletFactory
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const lightWalletFactoryABI = [
  {
    stateMutability: "nonpayable",
    type: "constructor",
    inputs: [
      {
        name: "_entryPoint",
        internalType: "contract IEntryPoint",
        type: "address",
      },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [],
    name: "accountImplementation",
    outputs: [
      { name: "", internalType: "contract LightWallet", type: "address" },
    ],
  },
  {
    stateMutability: "nonpayable",
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "salt", internalType: "uint256", type: "uint256" },
    ],
    name: "createAccount",
    outputs: [
      { name: "ret", internalType: "contract LightWallet", type: "address" },
    ],
  },
  {
    stateMutability: "view",
    type: "function",
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "salt", internalType: "uint256", type: "uint256" },
    ],
    name: "getAddress",
    outputs: [{ name: "", internalType: "address", type: "address" }],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__.
 */
export function useLightWalletRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"entryPoint"`.
 */
export function useLightWalletEntryPoint<
  TFunctionName extends "entryPoint",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "entryPoint",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"getDeposit"`.
 */
export function useLightWalletGetDeposit<
  TFunctionName extends "getDeposit",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "getDeposit",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"getNonce"`.
 */
export function useLightWalletGetNonce<
  TFunctionName extends "getNonce",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "getNonce",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"isValidSignature"`.
 */
export function useLightWalletIsValidSignature<
  TFunctionName extends "isValidSignature",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "isValidSignature",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"onERC1155BatchReceived"`.
 */
export function useLightWalletOnErc1155BatchReceived<
  TFunctionName extends "onERC1155BatchReceived",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "onERC1155BatchReceived",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"onERC1155Received"`.
 */
export function useLightWalletOnErc1155Received<
  TFunctionName extends "onERC1155Received",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "onERC1155Received",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"onERC721Received"`.
 */
export function useLightWalletOnErc721Received<
  TFunctionName extends "onERC721Received",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "onERC721Received",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"owner"`.
 */
export function useLightWalletOwner<
  TFunctionName extends "owner",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "owner",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"proxiableUUID"`.
 */
export function useLightWalletProxiableUuid<
  TFunctionName extends "proxiableUUID",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "proxiableUUID",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"supportsInterface"`.
 */
export function useLightWalletSupportsInterface<
  TFunctionName extends "supportsInterface",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "supportsInterface",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"tokensReceived"`.
 */
export function useLightWalletTokensReceived<
  TFunctionName extends "tokensReceived",
  TSelectData = ReadContractResult<typeof lightWalletABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof lightWalletABI, TFunctionName, TSelectData>,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletABI,
    functionName: "tokensReceived",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__.
 */
export function useLightWalletWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          string
        >["request"]["abi"],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof lightWalletABI, TFunctionName, TMode> & {
        abi?: never;
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, TFunctionName, TMode>({
    abi: lightWalletABI,
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"addDeposit"`.
 */
export function useLightWalletAddDeposit<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "addDeposit"
        >["request"]["abi"],
        "addDeposit",
        TMode
      > & { functionName?: "addDeposit" }
    : UseContractWriteConfig<typeof lightWalletABI, "addDeposit", TMode> & {
        abi?: never;
        functionName?: "addDeposit";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "addDeposit", TMode>({
    abi: lightWalletABI,
    functionName: "addDeposit",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"execute"`.
 */
export function useLightWalletExecute<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "execute"
        >["request"]["abi"],
        "execute",
        TMode
      > & { functionName?: "execute" }
    : UseContractWriteConfig<typeof lightWalletABI, "execute", TMode> & {
        abi?: never;
        functionName?: "execute";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "execute", TMode>({
    abi: lightWalletABI,
    functionName: "execute",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"executeBatch"`.
 */
export function useLightWalletExecuteBatch<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "executeBatch"
        >["request"]["abi"],
        "executeBatch",
        TMode
      > & { functionName?: "executeBatch" }
    : UseContractWriteConfig<typeof lightWalletABI, "executeBatch", TMode> & {
        abi?: never;
        functionName?: "executeBatch";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "executeBatch", TMode>({
    abi: lightWalletABI,
    functionName: "executeBatch",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"initialize"`.
 */
export function useLightWalletInitialize<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "initialize"
        >["request"]["abi"],
        "initialize",
        TMode
      > & { functionName?: "initialize" }
    : UseContractWriteConfig<typeof lightWalletABI, "initialize", TMode> & {
        abi?: never;
        functionName?: "initialize";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "initialize", TMode>({
    abi: lightWalletABI,
    functionName: "initialize",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"upgradeTo"`.
 */
export function useLightWalletUpgradeTo<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "upgradeTo"
        >["request"]["abi"],
        "upgradeTo",
        TMode
      > & { functionName?: "upgradeTo" }
    : UseContractWriteConfig<typeof lightWalletABI, "upgradeTo", TMode> & {
        abi?: never;
        functionName?: "upgradeTo";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "upgradeTo", TMode>({
    abi: lightWalletABI,
    functionName: "upgradeTo",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"upgradeToAndCall"`.
 */
export function useLightWalletUpgradeToAndCall<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "upgradeToAndCall"
        >["request"]["abi"],
        "upgradeToAndCall",
        TMode
      > & { functionName?: "upgradeToAndCall" }
    : UseContractWriteConfig<
        typeof lightWalletABI,
        "upgradeToAndCall",
        TMode
      > & {
        abi?: never;
        functionName?: "upgradeToAndCall";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "upgradeToAndCall", TMode>({
    abi: lightWalletABI,
    functionName: "upgradeToAndCall",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"validateUserOp"`.
 */
export function useLightWalletValidateUserOp<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "validateUserOp"
        >["request"]["abi"],
        "validateUserOp",
        TMode
      > & { functionName?: "validateUserOp" }
    : UseContractWriteConfig<typeof lightWalletABI, "validateUserOp", TMode> & {
        abi?: never;
        functionName?: "validateUserOp";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "validateUserOp", TMode>({
    abi: lightWalletABI,
    functionName: "validateUserOp",
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"withdrawDepositTo"`.
 */
export function useLightWalletWithdrawDepositTo<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletABI,
          "withdrawDepositTo"
        >["request"]["abi"],
        "withdrawDepositTo",
        TMode
      > & { functionName?: "withdrawDepositTo" }
    : UseContractWriteConfig<
        typeof lightWalletABI,
        "withdrawDepositTo",
        TMode
      > & {
        abi?: never;
        functionName?: "withdrawDepositTo";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletABI, "withdrawDepositTo", TMode>({
    abi: lightWalletABI,
    functionName: "withdrawDepositTo",
    ...config,
  } as any);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__.
 */
export function usePrepareLightWalletWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, TFunctionName>,
    "abi"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, TFunctionName>);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"addDeposit"`.
 */
export function usePrepareLightWalletAddDeposit(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "addDeposit">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "addDeposit",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "addDeposit">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"execute"`.
 */
export function usePrepareLightWalletExecute(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "execute">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "execute",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "execute">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"executeBatch"`.
 */
export function usePrepareLightWalletExecuteBatch(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "executeBatch">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "executeBatch",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "executeBatch">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"initialize"`.
 */
export function usePrepareLightWalletInitialize(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "initialize">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "initialize",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "initialize">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"upgradeTo"`.
 */
export function usePrepareLightWalletUpgradeTo(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "upgradeTo">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "upgradeTo",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "upgradeTo">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"upgradeToAndCall"`.
 */
export function usePrepareLightWalletUpgradeToAndCall(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "upgradeToAndCall">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "upgradeToAndCall",
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof lightWalletABI,
    "upgradeToAndCall"
  >);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"validateUserOp"`.
 */
export function usePrepareLightWalletValidateUserOp(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "validateUserOp">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "validateUserOp",
    ...config,
  } as UsePrepareContractWriteConfig<typeof lightWalletABI, "validateUserOp">);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletABI}__ and `functionName` set to `"withdrawDepositTo"`.
 */
export function usePrepareLightWalletWithdrawDepositTo(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletABI, "withdrawDepositTo">,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletABI,
    functionName: "withdrawDepositTo",
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof lightWalletABI,
    "withdrawDepositTo"
  >);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__.
 */
export function useLightWalletEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, TEventName>,
    "abi"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, TEventName>);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__ and `eventName` set to `"AdminChanged"`.
 */
export function useLightWalletAdminChangedEvent(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, "AdminChanged">,
    "abi" | "eventName"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    eventName: "AdminChanged",
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, "AdminChanged">);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__ and `eventName` set to `"BeaconUpgraded"`.
 */
export function useLightWalletBeaconUpgradedEvent(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, "BeaconUpgraded">,
    "abi" | "eventName"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    eventName: "BeaconUpgraded",
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, "BeaconUpgraded">);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__ and `eventName` set to `"Initialized"`.
 */
export function useLightWalletInitializedEvent(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, "Initialized">,
    "abi" | "eventName"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    eventName: "Initialized",
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, "Initialized">);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__ and `eventName` set to `"LightWalletInitialized"`.
 */
export function useLightWalletLightWalletInitializedEvent(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, "LightWalletInitialized">,
    "abi" | "eventName"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    eventName: "LightWalletInitialized",
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, "LightWalletInitialized">);
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link lightWalletABI}__ and `eventName` set to `"Upgraded"`.
 */
export function useLightWalletUpgradedEvent(
  config: Omit<
    UseContractEventConfig<typeof lightWalletABI, "Upgraded">,
    "abi" | "eventName"
  > = {} as any,
) {
  return useContractEvent({
    abi: lightWalletABI,
    eventName: "Upgraded",
    ...config,
  } as UseContractEventConfig<typeof lightWalletABI, "Upgraded">);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletFactoryABI}__.
 */
export function useLightWalletFactoryRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof lightWalletFactoryABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<
      typeof lightWalletFactoryABI,
      TFunctionName,
      TSelectData
    >,
    "abi"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletFactoryABI,
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletFactoryABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletFactoryABI}__ and `functionName` set to `"accountImplementation"`.
 */
export function useLightWalletFactoryAccountImplementation<
  TFunctionName extends "accountImplementation",
  TSelectData = ReadContractResult<typeof lightWalletFactoryABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<
      typeof lightWalletFactoryABI,
      TFunctionName,
      TSelectData
    >,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletFactoryABI,
    functionName: "accountImplementation",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletFactoryABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link lightWalletFactoryABI}__ and `functionName` set to `"getAddress"`.
 */
export function useLightWalletFactoryGetAddress<
  TFunctionName extends "getAddress",
  TSelectData = ReadContractResult<typeof lightWalletFactoryABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<
      typeof lightWalletFactoryABI,
      TFunctionName,
      TSelectData
    >,
    "abi" | "functionName"
  > = {} as any,
) {
  return useContractRead({
    abi: lightWalletFactoryABI,
    functionName: "getAddress",
    ...config,
  } as UseContractReadConfig<
    typeof lightWalletFactoryABI,
    TFunctionName,
    TSelectData
  >);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletFactoryABI}__.
 */
export function useLightWalletFactoryWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletFactoryABI,
          string
        >["request"]["abi"],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<
        typeof lightWalletFactoryABI,
        TFunctionName,
        TMode
      > & {
        abi?: never;
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletFactoryABI, TFunctionName, TMode>({
    abi: lightWalletFactoryABI,
    ...config,
  } as any);
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link lightWalletFactoryABI}__ and `functionName` set to `"createAccount"`.
 */
export function useLightWalletFactoryCreateAccount<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends "prepared"
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof lightWalletFactoryABI,
          "createAccount"
        >["request"]["abi"],
        "createAccount",
        TMode
      > & { functionName?: "createAccount" }
    : UseContractWriteConfig<
        typeof lightWalletFactoryABI,
        "createAccount",
        TMode
      > & {
        abi?: never;
        functionName?: "createAccount";
      } = {} as any,
) {
  return useContractWrite<typeof lightWalletFactoryABI, "createAccount", TMode>(
    {
      abi: lightWalletFactoryABI,
      functionName: "createAccount",
      ...config,
    } as any,
  );
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletFactoryABI}__.
 */
export function usePrepareLightWalletFactoryWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof lightWalletFactoryABI, TFunctionName>,
    "abi"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletFactoryABI,
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof lightWalletFactoryABI,
    TFunctionName
  >);
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link lightWalletFactoryABI}__ and `functionName` set to `"createAccount"`.
 */
export function usePrepareLightWalletFactoryCreateAccount(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof lightWalletFactoryABI,
      "createAccount"
    >,
    "abi" | "functionName"
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: lightWalletFactoryABI,
    functionName: "createAccount",
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof lightWalletFactoryABI,
    "createAccount"
  >);
}
