ignores:
  - "@babel/core"
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - "@types/node"
  - typescript
  - "@babel/core"
  - "@types/node"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - critters
  - "@lightdotso/styles"
  - "@next/bundle-analyzer"
  - "@sentry-internal/feedback"
  - "@sentry/react"
  - "@upstash/edge-flags"
  - "@upstash/kafka"
  - "@upstash/ratelimit"
  - "@upstash/redis"
  - "@sentry/integrations"
