ignores:
  - "@babel/core"
  - "@lightdotso/kysely"
  - "@lightdotso/prisma"
  - "@prisma/client"
  - "@tanstack/react-query-devtools"
  - "@tanstack/react-query-next-experimental"
  - kysely-postgres-js
  - postgres
  - prisma
  - server-only
  - superjson
  - "@types/node"
  - eslint-config-prettier
  - eslint-import-resolver-typescript
  - "@playwright/test"
  - checkly
  - "@lightdotso/tsconfig"
  - "@types/react-dom"
  - autoprefixer
  - postcss
  - tailwindcss
  - jsonc-eslint-parser
  - "@next/eslint-plugin-next"
  - eslint-plugin-turbo
  - immer
  - "@lightdotso/wagmi"
  - blurhash
  - sonner
  - "@prisma/nextjs-monorepo-workaround-plugin"
  - "@lukemorales/query-key-factory"
  - zustand
  - "@radix-ui/react-dropdown-menu"
  - react-blurhash
  - class-variance-authority
  - "@vercel/toolbar"
  - "@lightdotso/params"
  - "@next/bundle-analyzer"
  - "@lightdotso/const"
  - "@lightdotso/demo"
  - wagmi
  - siwe
  - permissionless
  - "@sentry/node"
  - "@hookform/devtools"
  - "@upstash/kafka"
  - "@upstash/ratelimit"
  - "@upstash/redis"
  - "pusher-js"
  - "@sentry-internal/feedback"
  - "@sentry/react"
  - "@sentry/integrations"
  - react-is
  - recharts
