name: Cspell
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  cspell:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: Spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          config: "./cspell.json"
          root: "."
          use_cspell_files: true
          incremental_files_only: false
