name: Extension
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    types:
      - labeled
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  extension-turbo:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      trigger: ${{ steps.turbo.outputs.trigger }}
    steps:
      - name: Turbo Trigger
        id: turbo
        uses: wallet-rs/wallet-rs/.github/actions/turbo-trigger@main
        with:
          workspace: "@lightdotso/extension"
  extension:
    if: needs.extension-turbo.outputs.trigger == 'true'
    needs:
      - extension-turbo
    runs-on: ubuntu-latest
    env:
      TURBO_API: ${{ secrets.TURBO_API }}
      TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    permissions:
      contents: read
    timeout-minutes: 90
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: Node Install
        uses: wallet-rs/wallet-rs/.github/actions/node-install@main
      - name: Node Build
        run: |
          pnpm run build:turbo --filter={apps/extension}
      - if: github.event_name == 'pull_request'
        name: Chrome upload
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: apps/extension/chrome.zip
          extension-id: emflafmoooolgldefbdhjeifjnhhhedc
          publish-target: trustedTesters
          publish: false
          client-id: ${{ secrets.EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.EXTENSION_CLIENT_SECRET }}
          refresh-token: ${{ secrets.EXTENSION_REFRESH_TOKEN }}
      - if: github.event_name == 'merge_group'
        continue-on-error: true
        name: Chrome upload
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: apps/extension/chrome.zip
          extension-id: emflafmoooolgldefbdhjeifjnhhhedc
          publish: true
          client-id: ${{ secrets.EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.EXTENSION_CLIENT_SECRET }}
          refresh-token: ${{ secrets.EXTENSION_REFRESH_TOKEN }}
  extension-check:
    if: always()
    needs:
      - extension-turbo
      - extension
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: extension
          jobs: ${{ toJSON(needs) }}
