name: Extension
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
jobs:
  extension-build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Node Install
        uses: wallet-rs/wallet-rs/.github/actions/node-install@main
      - name: Node Build
        run: |
          pnpm run build --filter={apps/extension}
      - name: Chrome upload
        uses: mnao305/chrome-extension-upload@v4.0.1
        with:
          file-path: apps/extension/chrome.zip
          extension-id: emflafmoooolgldefbdhjeifjnhhhedc
          client-id: ${{ secrets.EXTENSION_CLIENT_ID }}
          client-secret: ${{ secrets.EXTENSION_CLIENT_SECRET }}
          refresh-token: ${{ secrets.EXTENSION_REFRESH_TOKEN }}
  node-check:
    if: always()
    needs:
      - extension-build
    runs-on: ubuntu-latest
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
