name: Fly
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  release:
    types: created
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  fly-wait-docker:
    if: github.event_name == 'push' || startsWith(github.ref, 'refs/tags/@lightdotso/bin') && github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Sleep for 30 seconds
        run: |
          sleep 30s
      - name: Wait Docker
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: docker-build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
          allowed-conclusions: success
  fly-deploy-grafana:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Fly Install
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        run: flyctl deploy --remote-only
        working-directory: ./fly/grafana
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  fly-deploy-serve:
    runs-on: ubuntu-latest
    needs:
      - fly-wait-docker
    timeout-minutes: 30
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Fly Install
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        run: flyctl deploy --remote-only
        working-directory: ./fly/serve
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  fly-deploy-indexer:
    runs-on: ubuntu-latest
    needs:
      - fly-wait-docker
    timeout-minutes: 30
    steps:
      - name: Fetch Head
        uses: actions/checkout@v3
      - name: Fly Install
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly Deploy
        run: flyctl deploy --remote-only
        working-directory: ./fly/indexer
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  fly-check:
    if: always()
    needs:
      - fly-wait-docker
      - fly-deploy-grafana
      - fly-deploy-serve
      - fly-deploy-indexer
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: fly-wait-docker,fly-deploy-serve,fly-deploy-indexer
          jobs: ${{ toJSON(needs) }}
