name: GraphQL
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  graphql-update-schema:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: Node Install
        uses: wallet-rs/wallet-rs/.github/actions/node-install@main
      - name: Run Introspection
        uses: obmarg/action-graphql-introspect@main
        with:
          server-url: https://api.thegraph.com/subgraphs/name/lightdotso/mainnet
          output-file: crates/graphql/schemas/graph.graphql
      - name: Run Fix
        run: |
          pnpm run fix
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.BOT_TOKEN }}
          commit-message: "chore: Update GraphQL Schema"
          branch: graphql-schema-updates
          title: "chore: Update GraphQL Schema"
