name: PR
on:
  pull_request:
  # pull_request_target:
  #   types:
  #     - opened
  #     - edited
  #     - synchronize
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  pr-lint:
    name: PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: PR Validate
        uses: wallet-rs/wallet-rs/.github/actions/pr-validate@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  pr-check:
    if: always()
    needs:
      - pr-lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
