name: PR
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: PR Validate
        uses: wallet-rs/wallet-rs/.github/actions/pr-validate@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
