name: Python
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    types:
      - labeled
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  python-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: Rye Install
        uses: sksat/setup-rye@v0.16.0
      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Ruff Lint
        uses: chartboost/ruff-action@v1
      - name: Ruff Format
        uses: chartboost/ruff-action@v1
        with:
          args: format
  python-check:
    if: always()
    needs:
      - python-lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
