name: Python
on:
  push:
    branches:
      - main
  pull_request:
  pull_request_target:
    types:
      - labeled
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  python-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: read
    steps:
      - name: Fetch Head
        uses: actions/checkout@v4
      - name: Set up Rye
        run: curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash
        shell: bash
      - name: Add Rye to PATH
        run: echo "$HOME/.rye/shims" >> $GITHUB_PATH
        shell: bash
      - name: Install dependencies
        run: |
          rye sync --no-lock
      - name: Set up Ruff
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
  python-check:
    if: always()
    needs:
      - python-lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
