name: Vercel
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
env:
  TURBO_API: ${{ secrets.TURBO_API }}
  TURBO_REMOTE_CACHE_SIGNATURE_KEY: ${{ secrets.TURBO_REMOTE_CACHE_SIGNATURE_KEY }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
jobs:
  vercel-turbo:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        app: [ai, app, blog, changelog, docs, paper, explorer, frames, home, paper, proposals, storybook]
    outputs:
      trigger: ${{ steps.turbo.outputs.trigger }}
    steps:
      - name: Turbo Trigger
        id: turbo
        uses: wallet-rs/wallet-rs/.github/actions/turbo-trigger@main
        with:
          workspace: "@lightdotso/${{ matrix.app }}"
  vercel-deploy:
    needs: vercel-turbo
    if: needs.vercel-turbo.outputs.trigger == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [ai, app, blog, changelog, docs, paper, explorer, frames, home, paper, proposals, storybook]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node Install
        uses: wallet-rs/wallet-rs/.github/actions/node-install@main
      - name: Turbo Build App
        run: |
          pnpm turbo run build --filter=@lightdotso/${{ matrix.app }}
  vercel-check:
    needs:
      - vercel-turbo
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Check All Green
        uses: re-actors/alls-green@release/v1
        with:
          allowed-skips: vercel-turbo
          jobs: ${{ toJSON(needs) }}
