ignores:
  - "@babel/core"
  - "@lightdotso/tsconfig"
  - "@types/react"
  - "@types/react-dom"
  - "@types/node"
  - typescript
  - "@babel/core"
  - "@types/node"
  - autoprefixer
  - postcss
  - tailwindcss
  - typescript
  - critters
  - "@lightdotso/styles"
  - "@next/bundle-analyzer"
  - "@coinbase/onchainkit"
  - "@lightdotso/services"
  - "@vercel/og"
  - viem
  - "@sentry/integrations"
